- hosts: localhost
  name: Bootstrap local Mac as a development machine
  connection: local
  roles:
    - setup_homebrew_pkgs
    - configure_git
    - configure_fish
    - setup_ssh_key
    - install_volta
    - install_nodejs
    - setup_dotfiles
