- hosts: localhost
  name: Bootstrap local Ubuntu as a development machine
  connection: local
  roles:
    - install_openssh
    - harden_ssh_login
    - update_upgrade_pkgs
    - setup_apt_pkgs
    - harden_firewall
    - configure_git
    - configure_fish
    - setup_ssh_key
    - install_volta
    - install_nodejs
    - install_go
    - setup_dotfiles
