- hosts: ubuntu_dev
  name: Bootstrap remote Ubuntu as a development machine
  roles:
    - update_upgrade_pkgs
    - enable_unattended_upgrades
    - setup_apt_pkgs
    - harden_firewall
    - configure_git
    - configure_fish
    - setup_ssh_key
    - install_volta
    - install_nodejs
    - install_go
    - setup_dotfiles
