# Setup dotfiles using Stow on Mac and Ubuntu

- name: Check if Stow is already installed on Mac
  stat:
    path: /opt/homebrew/bin/stow
  register: stow_check
  when: ansible_distribution == 'MacOSX'

- name: Check if Stow is already installed on Ubuntu
  stat:
    path: /usr/bin/stow
  register: stow_check
  when: ansible_distribution == 'Ubuntu'

- name: Failing if Stow is not installed
  fail:
    msg: Stow is missing
  when: not stow_check.stat.exists

- name: Remove existing dotfiles folder
  file:
    path: ~/dotfiles
    state: absent

- name: Copy dotfiles
  copy:
    src: dotfiles
    dest: ~/

- name: Run a template
  template:
    src: config.fish.j2
    dest: ~/dotfiles/fish/.config/fish/config.fish

- name: Stow fish dotfiles
  shell:
    chdir: ~/dotfiles
    cmd: stow --adopt -t ~ fish

- name: Stow tmux dotfiles
  shell:
    chdir: ~/dotfiles
    cmd: stow --adopt -t ~ tmux

- name: Stow vim dotfiles
  shell:
    chdir: ~/dotfiles
    cmd: stow --adopt -t ~ vim
