# Perform basic SSH security checks

- name: Only allow SSH from ipv4 on Ubuntu
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?AddressFamily'
    line: "AddressFamily inet"
    backup: true
  when: ansible_distribution == 'Ubuntu'

- name: Disable root SSH login on Ubuntu
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin no"
    backup: true
  when: ansible_distribution == 'Ubuntu'

- name: Disable SSH password authentication on Ubuntu
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication no"
    backup: true
  when: ansible_distribution == 'Ubuntu'

- name: Restart SSHD on Ubuntu
  become: true
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: ansible_distribution == 'Ubuntu'
