- name: Install Open SSH client
  become: yes
  apt:
    name: openssh-client
  when: ansible_distribution == 'Ubuntu'

- name: Install Open SSH server
  become: yes
  apt:
    name: openssh-server
  when: ansible_distribution == 'Ubuntu'
