- name: Install Open SSH client
  become: true
  ansible.builtin.apt:
    name: openssh-client
  when: ansible_distribution == 'Ubuntu'

- name: Install Open SSH server
  become: true
  ansible.builtin.apt:
    name: openssh-server
  when: ansible_distribution == 'Ubuntu'
