# Update and upgrade Apt on Unbuntu

- name: Run apt update and upgrade on Ubuntu
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day
  when: ansible_distribution == 'Ubuntu'
