# As a root, create non root user

- name: Create non root user
  user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    state: present

- name: Copy SSH public key
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ ssh_pub_key }}"

- name: Add user to sudo
  user:
    name: "{{ user }}"
    groups: sudo
    append: yes
