# Enable unattended upgrades on Ubuntu

- name: Install unattended-upgrades on Ubuntu
  become: yes
  apt:
    name: unattended-upgrades
  when: ansible_distribution == 'Ubuntu'

- name: Enable unattended-upgrades on Ubuntu
  become: yes
  shell:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
  when: ansible_distribution == 'Ubuntu'
